disabled_rules: # rule identifiers to exclude from running
- force_cast
- large_tuple
- trailing_whitespace
- mark
- comment_spacing
- empty_enum_arguments
- control_statement
- statement_position 

#Customized Rules
line_length:
    warning: 200
    error: 1000
file_length:
    warning: 600
    error: 750
vertical_whitespace:
    warning: 2
    max_empty_lines: 0
    
#force_cast: warning
identifier_name:
    excluded: # excluded via string array
        - id
        - URL
        - GlobalAPIKey
        - i
        - j
        - k
    allowed_symbols:
        -_
    validates_start_with_lowercase: false

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Frameworks/CoreModule/NetFox
- Frameworks/CoreModule/DI/Resolver.swift
- Frameworks/ServicesModule/InternetConnectivityService/Reachability
- Frameworks/CustomComponentsModule/BottomSheetContainerViewController
- Frameworks/ServicesModule/DataCachingServices/KeyChainDataCachingService/Keychain.swift

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
